-- EDOS Poultry360: AI/ML engine follow-up (spec §49-55) — widen the
-- notification type check constraint to add two new Decision Center
-- (spec §53) alert types, generated by the same lazy
-- ensureDueNotifications() path as the existing five (see
-- src/lib/data/notifications.ts).

alter table public.poultryedos_notifications drop constraint poultryedos_notifications_type_check;

alter table public.poultryedos_notifications add constraint poultryedos_notifications_type_check
  check (type in (
    'vaccination_due', 'low_stock', 'mortality_alert', 'subscription',
    'support_ticket', 'task_assigned', 'general',
    'production_decline', 'feed_stockout'
  ));
